### ISSUE TITLE
not able install plugin only with plugin.php

### ISSUE THREAD

**Issue by Jimmi08** [Jimmi08/content#15]
Normally plugin.php should be enough
 
ilayangudi commented 40 minutes ago
@Jimmi08 It appears that plugin.xml is missing. I am not sure whether it is required. Additionally, this plugin is not listed under the 'Find Plugins' menu under the Plugin Manager.

**Comment by Jimmi08** [comment]
![image](https://cloud.githubusercontent.com/assets/5429548/14404822/c69eafda-fe7f-11e5-8445-16a3d2d928eb.png)

**Comment by ilayangudi** [comment]
@Jimmi08  I have installed the plugin and it says the not able to create new tables as I didnt delete the existing tables. I am able to see all the articles in the Admin page. The Menu is not displayed in the Menu Manager for me to place the Articles in the Area 1, Area 2 and etc.  I go to Settings -> Options, It displays the content categories. I selected one category and I want to change settings. It displays the list of options in the Tabs. But, 'update options; is not working. Clicking the button and no response.  Please check.

**Comment by ilayangudi** [comment]
@Jimmi08  Please let me know how to create Content Menu into the Menu Manager.

**Comment by Jimmi08** [comment]
@ilayangudi the error about not creating new tables are normal and correct, it doesn't influence anything. Tables are exactly the same. No changes.

You can copy menu from your v1 installation (if you deleted all old folder, it needs to be create again, With new category it should works, but I didn't test this.
Do you know where your menus are saved in v1 version? 

If I know your email, I could you create account at my site with access to content plugin here and you could test it there and write me what is wrong. Or you could test registration on e107.sk.  Don't write your email here, please. Or send me PM on e107help.org (nick Jimako).

I really would like to improve this plugin, but I am not using it now, somebody else need to test it and tell me what is wrong.
